### ISSUE TITLE
Boton de Parar apuesta automatica

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#11]
Hacer un boton con la opcion de Parar apuesta automática (indefinida)
La apuesta automatica esta definida en un input oculto

**Comment by Manuestaire** [comment]
Damage comentó que poca gente sabe crear scripts, pero sí lo único que bloquea la apuesta automática es la visibilidad del input es muy fácil activarla mediante script o editando código con google chrome, estaría bien hacer un chequeo via php dentro de la funcion de apuesta automática, para ver si el usuario tiene permiso para hacerla.

**Comment by NiciusB** [comment]
Si bueno, no hay forma de bloquear scripts del tipo de yo creaba, pero podemos ponerlo mas difícil...
El caso es que si no lo tienes comprado, no te saldría el input ni el javascript para apostar automaticamente

**Comment by Manuestaire** [comment]
Relaccionado con: https://github.com/Manuestaire/megacorporation/issues/7
