### ISSUE TITLE
Nuevo Formato en Edificios

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#12]
Está pendiente cambiar el diseño para la sección de edificios.
- Eliminar los "tier" o categorías de edificios de la vista. Si quereís que sigan estando se pondrían en las imágenes de los edificios, pero de eso me ocuparía yo.
- Optimizar el código, al quitar las categorías habrá código que quede sin utilidad, etc... Aparte, ahora mismo se repite en dos sitios distintos el mismo esquema que se usa para mostrar la información de los edificios.

**Comment by NiciusB** [comment]
Hecho

**Comment by Manuestaire** [comment]
Voy a reabrir porque aún hay que hacer cosas aquí.

**Comment by NiciusB** [comment]
Ah si? xD
Pues ponlas en el primer post para poder saber cuales son ;D

**Comment by Manuestaire** [comment]
He añadido dos cosillas ahí arriba, que son las que os atañen.

**Comment by Manuestaire** [comment]
De momento doy esto por terminado, en otra pasada hay que cambiar la forma en que se muestra la información de cada edificio; ponerlo con tablas para que los espacios en vez de generarse al principio y final del contenido se generen entre la descripción y las características.
