### ISSUE TITLE
Nueva operacion: Robar

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#13]
Pues eso, hacer que ganes una décima de lo que ganas saboteando y que robando ganas lo que ganas ahora saboteando...
Al robar no rompes edificios, por supuesto.
Podríamos hacer un rand entre 0,7 y 1,3 que se multiplicara por el dinero que ganas
También podríamos ampliar el máximo de operaciones a 4.

**Comment by Manuestaire** [comment]
Cuál sería la ventaja de robar respecto a sabotear?

**Comment by NiciusB** [comment]
Pues ganas dinero, con este cambio no ganas casi dinero al sabotear

**Comment by Manuestaire** [comment]
Cómo ya estamos hablando de esto en el #17 cierro...
