### ISSUE TITLE
Hacer la pagina de soporte

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#15]
Hacer la pagina de soporte donde la gente crea tickets y los Go's o los Admins (nosotros) los contestáramos y avisara en el menu, por supuesto

**Comment by DamageESP** [comment]
He creado una tabla llamada soporte donde iran los tickets que manden, y la pagina de soporte me pondre a hacerla en breve.

**Comment by DamageESP** [comment]
Doy esto por acabado por ahora.
