### ISSUE TITLE
Error en el precio de edificios al comprar

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#22]
Al verlo sale bien, pero al comprar te cobra de menos, y si pones mas de uno te cobra precios desorbitados xD

**Comment by DamageESP** [comment]
Habría que hacer que calculase el precio total con los incrementos antes de hacer el action.

**Comment by NiciusB** [comment]
Tambien, eso sería javascript xD pero yo digo en el php

**Comment by DamageESP** [comment]
Esta solucionado ya?

**Comment by NiciusB** [comment]
De momento no he descubierto ningun bug.
Cerrado mientras no se descubran fallos
