### ISSUE TITLE
Recursos de clanes

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#23]
He empezado a hacer los recursos de los clanes.
Estan al final del cron de cada minuto, a quien le interese xD

**Comment by DamageESP** [comment]
No se que ha pasado pero se ven todos los numeros de los recursos con decimales.

Por cierto ya se pueden enviar solicitudes, pero falta hacer la seccion administrar megacorp y esas cosillas.

**Comment by DamageESP** [comment]
El dinero de mi alianza se ve en negativo. No se por que xD

**Comment by NiciusB** [comment]
Hace unos dias solucioné un bug que restaba dinero a todas las alianzas al sacar dinero de la tuya.
Además, solo generabais 50€ al dia, y lo normal son 100000€
Ya esta arrreglado

**Comment by NiciusB** [comment]
Ya puedes sacar y meter todos los recursos.
Faltan las investigaciones

**Comment by NiciusB** [comment]
Investigaciones terminadas, pero faltan cosas como estadisticas de aportaciones
El sistema es:
Usuarios aportan dinero que va para el fondo de investigaciones
Presidente tambien puede aportar, y administra las investigaciones que se suben.
Se pueden añadir cosas como impuesto de alianza (El presidente pone un impuesto sobre los ingresos, que ira al fondo de la alianza.) o otros

**Comment by DamageESP** [comment]
Buenísma idea lo del almacén de fondos del clan.

Buen trabajo.

**Comment by NiciusB** [comment]
Jajja gracias, estoy trabajando en los impuestos de alianza

**Comment by NiciusB** [comment]
Añadidos los impuestos de alianza y funcionando.
Añadido un contador de aportaciones.

**Comment by NiciusB** [comment]
Cierro, creo que no hace falta nada mas que meter de momento.

**Comment by DamageESP** [comment]
Falta el historial del almacen: entradas y salidas de recursos.

**Comment by NiciusB** [comment]
Ops es verdad xD abro hasta que los haga

**Comment by NiciusB** [comment]
Historial hecho, faltan limites

**Comment by NiciusB** [comment]
Terminados límites, ya que se implementaron con los rangos

**Comment by DamageESP** [comment]
Hay un pequeño problema. En las aportaciones individuales de los usuarios, hay un límite, que es 2.147.483.647 € una vez alcanzada esta cifra no avanza más.

**Comment by NiciusB** [comment]
Arreglado.
Algún bug mas o cerramos?

**Comment by DamageESP** [comment]
Por ahora nada más.
Cierro.
