### ISSUE TITLE
Link Mensajes Recibidos

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#24]
Hay un problema con las tabs en los mensajes privados, cuando te llega un mensaje y haces click al link para verlo en el menú, te lleva siempre al tab principal, en lugar de al del tipo de mensaje. Habría que hacer que la url dependa del tipo del mensaje.

Además, estaría bien que saliesen los números de los mensajes recibidor en cada pestaña (tab).

**Comment by Manuestaire** [comment]
@NiciusB  te asigno el ticket porque damage me dijo que no sabía como hacerlo

**Comment by NiciusB** [comment]
Te lleva directamente al mensaje que hayas recibido, segun el tipo
pendiente corregir errores

**Comment by Manuestaire** [comment]
Falta entonces que salga el numero de mensajes recibidos de cada tipo en cada titulillo del tab. @NiciusB

**Comment by NiciusB** [comment]
Hecho
