### ISSUE TITLE
Rankings

### ISSUE THREAD

**Issue by DamageESP** [Manuestaire/megacorporation#31]
Hay que hacer rankings de Investigaciones, Fama y de Megacorps!! Os cito para que os salga en novedades.

@Manuestaire
@NiciusB

**Comment by NiciusB** [comment]
Okey los haré ;D
He vuelto de unas vacaciones xDD

**Comment by DamageESP** [comment]
Rankings de usuarios listos... xD

**Comment by DamageESP** [comment]
@NiciusB, necesito que pongas este comando "lower_case_table_names 2" para que en las búsquedas en la base de datos no sean CASE SENSITIVE, y se pueda buscar tanto en mayuscula como minuscula.

**Comment by NiciusB** [comment]
donde hay que ponerlo? xD

**Comment by DamageESP** [comment]
En un archivo que se llama "my.ini", dentro de la carpeta de MySQL.

**Comment by DamageESP** [comment]
Vale, ya lo he arreglado sin tener que cambiar eso.

**Comment by DamageESP** [comment]
@NiciusB necesito que arregles el rank de clanes por favor, no se como hacerlo xD.

Gracias, y esto es lo ultimo que falta por ahcer en los rankings, creo.

**Comment by DamageESP** [comment]
Estoy terminando esto.

**Comment by DamageESP** [comment]
@NiciusB Necesito una mano con esto, te he marcado donde empiezan los problemas, casi al final del todo:

http://pastebin.com/7Ey0VimL

Cuando pongo un user, me tira este error:

Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\rank.php:155) in C:\xampp\htdocs\rank.php on line 216

**Comment by NiciusB** [comment]
Subelo a la web y lo arreglo, asi puedo ver bien los errores xD

**Comment by NiciusB** [comment]
rank2.php funcionando bien, pero los estilos son los del localshot de damageesp por lo que se ve peor, supongo xD
Todos los links de rank2.php llevan a rank.php pero cuando lo pasemos a rank.php ya irá bien.

**Comment by NiciusB** [comment]
Los datos de rank_ingresos, rank_inves y rank_influencia de los clanes ya se calculan correctamente cada media hora.
Falta hacerles el rank paginado

**Comment by DamageESP** [comment]
La posicion empieza en 0 y no en 1 en el rank2.php

**Comment by NiciusB** [comment]
Era cambiar un numero ¬¬
Arreglado

**Comment by NiciusB** [comment]
Cambiado rank.php a rank_antiguo.php (archivo temporal por si las moscas)
Cambiado rank2.php a rank.php
Faltan los estilos del mismo

**Comment by DamageESP** [comment]
He puesto para que se listen 25 users por página.
Sigue sin funcionar lo de buscar un usuario que no esté en la página 0.

**Comment by DamageESP** [comment]
Ya funciona la búsqueda de usuarios en todos los rankings.

Queda arreglar el ranking de clanes.

**Comment by DamageESP** [comment]
He puesto una búsqueda en tiempo real en el ranking de usuarios.

Probadla y me decís que tal.

**Comment by NiciusB** [comment]
Está muy bien :)
cuando da errores sale bien, pero si no el usuario sale a la izquierda

**Comment by DamageESP** [comment]
Doy esto por acabado por ahora.
