### ISSUE TITLE
Seguridad en Formularios

### ISSUE THREAD

**Issue by DamageESP** [Manuestaire/megacorporation#35]
Hay que poner algun tipo de seguridad en los inputs, se puede inyectar todo tipo de código ahora mismo.

**Comment by DamageESP** [comment]
Hay que agregar a los datos la funcion PHP "htmlspecialchars($dato)" antes de ingresar los daros a la BD. Esto convertira los caracteres especiales como las comillas a &gt y cosas de esas.

Si encontrais mas funciones de seguridad ponedlas aqui.

**Comment by NiciusB** [comment]
sep.
yo tenía una funcion para poner striptags y evitar inyecciones sql a todos los POST y los GET, el problema es que si se utiliza habría que eliminar todas las mysql_escape_string() para evitar que las ' salieran como \' xDD

**Comment by NiciusB** [comment]
Bueno, yo creo que no hay problema en los forms al menos de momento.
Cerrado
