### ISSUE TITLE
Medallas de concursos

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#36]
Al ganar un concurso aparte del premio te dan una medalla que saldrá en tu perfil

**Comment by DamageESP** [comment]
Buena idea!

**Comment by NiciusB** [comment]
Jajaja en realidad no es mía, es de sacher-noseque xD
necesitaremos imagenes, @Manuestaire

**Comment by Manuestaire** [comment]
Yo hasta final de mes tengo bastante lío con los parciales de la uni, como para meterme con photoshop...

**Comment by NiciusB** [comment]
ok no problem jeje no hay prisa
