### ISSUE TITLE
LA GENTE NOS ESPERA !!

### ISSUE THREAD

**Issue by DamageESP** [Manuestaire/megacorporation#38]
@Manuestaire 
@NiciusB 

La gente en general esta en los foros pidiendo una version mejorada hecha por otros administradores. Si nos ponemos las pilas, podemos ser nosotros! En mi opinión, hay que cambiar aun más el juego! Los perfiles, los nombres de todo, etc.

**Comment by Manuestaire** [comment]
Jaja, buen issue.

Las cosas de palacio van despacio, qué os parece si para sacar provecho a este post vamos ecribiendo aquí prioridades.

Ahora mismo para mí:
 1.- Terminar el algoritmo de los ataques
 2.- Hacer al menos dos diseños para las tragaperras de los casinos.

**Tenemos 3 bugs pendientes, y 8 tareas en progreso...**

**Comment by DamageESP** [comment]
Mis prioridades:

1.- Terminar la bolsa
2.- Terminar el Keno
3.- Terminar el panel de administracion
4.- Aver lo que hago con el poker..
5.- Terminar el ranking de clanes (con ayuda de @NiciusB )

Y seguramente más, pero no recuerdo xD

**Comment by Manuestaire** [comment]
Yo a la bolsa no le daría tanta prioridad pero ok...

**Comment by NiciusB** [comment]
Yo tampoco xD primero soucionar bugs y hacer cosas basicas como los clanes

**Comment by Manuestaire** [comment]
@DamageESP @NiciusB 

A ver os digo como organizar prioridades con las labels:
1. Bugs - Máxima prioridad
2. En progreso - Ya se está trabajando en ello, y por tanto tiene prioridad por acabarlo.
3. Próxima tarea - La sugerencia está aceptada, y dentro de poco se trabajará en ello.
4. Próximamente - Sugerencia aceptada, pero con poca prioridad.

**Comment by Manuestaire** [comment]
@DamageESP  @NiciusB 

Tenemos **9 tareas "En Progreso"** hay que intentar irlas sacando, para ir cerrando cosas...

**Comment by garzonp** [comment]
HOLAAAAA CUAL ES EL CODIGO PARA JUGAR EN MEGACORP CONPINGO?

**Comment by Manuestaire** [comment]
Por favor no nos spammes y sigue las instrucciones que se envian al mandar un correo a megacorporation.game@gmail.com
