### ISSUE TITLE
Tabs de mensajes

### ISSUE THREAD

**Issue by DamageESP** [Manuestaire/megacorporation#40]
@niciusB
@manuestaire

Como soy gilipollas he jodido lo de las tabs en el clan y eso en cabecera.php, nose lo que falla pero en fin, no funciona. Estaba intentando poner esto:

http://css-tricks.com/bubble-point-tooltips-with-css3-jquery/

Decidme como hay q ponerlo y cerrad el issue. Gracias.

**Comment by NiciusB** [comment]
Borraste el css de las tabs:
< link href="css/perfil.css" rel="stylesheet" type="text/css" />
