### ISSUE TITLE
Cambio de estilo de web

### ISSUE THREAD

**Issue by DamageESP** [Manuestaire/megacorporation#41]
@manuestaire
@niciusb

El diseño no me gusta nada, hay que darle un ambiente empresarial, y por ello, voy a dejar unas capturas como el que no quiere la cosa.

P.D.: Imagenes sin Copyright. Son Creative Common o hechas por mí, como la imagen de perfil del clan.

http://gyazo.com/ed49e6be7d89406f03b1dd98149704ba

**Comment by Manuestaire** [comment]
El diseño del perfil del clan está bien, pero te falta incluir las pestañas para edificios e investigaciones...

Siento no estar haciendo nada ultimamente pero estoy bastante liado con la uni. Respecto a las tablas que estaís usando por todo el juego no están mal, pero los colores oscuros sin contrastes terminan por aburrir, más adelante me gustaría probar otros diseños para las tablas, porque no encajan bien con el diseño global.

**Comment by NiciusB** [comment]
Me gusta mucho mas que el actual :D Pero si, te faltan las tabs :+1:

**Comment by DamageESP** [comment]
Tabs listas. Las opciones de guerra, alianza y pna solo estaran disponibles para los presidentes. Añadidas sombras en texto. Os molan? A mi no mucho xD

http://gyazo.com/c5b0a2621114d791b10b45de5f466149

http://gyazo.com/537d727c7bad60afd8291e9b4ab86891

**Comment by NiciusB** [comment]
Realmente?
no mucho xDDD las tabs son muy cuadradas y feas en cuanto a colores, no?

**Comment by Manuestaire** [comment]
No os preocupeís de estilos, y dejad las tabs de momento como están, que ya me ocuparé yo cuando tenga tiempo de ir cambiando estilos por todas partes, preocuparos por la estructura...

**Comment by DamageESP** [comment]
Ah, y tambien he hecho para que se muestren 50 personas por página, y he añadido la columna rank donde se almacenara el puesto en el rank de ingresos, y tambien tengo la función aquí. La pongo por si la quiere revisar tathtat.

``` php
<?php

include("conn.php");
$qry= mysql_query("SELECT id FROM usuarios ORDER BY ingresos DESC");
$i = 1;
while ($row = mysql_fetch_array($qry)) {
    mysql_query("UPDATE usuarios SET rank = '$i' WHERE id='$row[id]'");
    $i++;
}

?>
```

**Comment by NiciusB** [comment]
Creo que está bien xD pero el primero va a ser 1 o 0? xD

**Comment by DamageESP** [comment]
1. lo he probado xD

**Comment by NiciusB** [comment]
Ya he metido los iconitos a atacar, espiar y ver perfil xD

**Comment by DamageESP** [comment]
Quereis que os vaya pasando los estilos que tengo? Por si los quereis usar para avanzar más rapido digo. Tengo todos los estilos en un CSS de unas 400 líneas. El header y el footer los quiero hacer de nuevo, pero necesito inspiración xD.

**Comment by Manuestaire** [comment]
A mi me parece que los estilos globales están bien y lo que hay que cambiar son los diseños de las tablas y de las páginas interiores, es un diseño elegante, y con colores claros que es fundamental, no creo que cambiar el diseño para meter negros y colores puros sea positivo...

En serio dejadme terminar el sieño que tengo en mente y luego cambiaís todo lo que queraís, una vez que haya terminado cambiaís lo que queraís sin preguntarme.

**Comment by DamageESP** [comment]
Desde mi punto de vista lo que hay que tratar es de cuando el usuario entre a la web se sienta como en una oficina empresarial, colores oscuros y serios. Pero termina tu el diseño para ver como quedaria.

**Comment by Manuestaire** [comment]
No se que concepto tienes de oficina, pero vamos yo he estado en las oficinas de electronic arts y te puedo decir que son todo cosas claras, normalmente blanco, con mobiliario o detalles en alguna pared de azules, verdes y rojos vivos...

Si al sitio al que la gente tiene que ir a trabajar encima lo haces deprimente, pues apaga y vámonos...

 https://www.google.es/search?q=oficina&oe=utf-8&aq=t&rls=org.mozilla:es-ES:official&client=firefox-a&um=1&ie=UTF-8&hl=es&tbm=isch&source=og&sa=N&tab=wi&ei=Wc-eUI6-HYy3hAfe9oDwDA&biw=1366&bih=665&sei=W8-eUMawNOa50QXEu4DIDQ

**Comment by NiciusB** [comment]
Yo creo que este se debería dejar a manuel, ya que el no programa php...
Asi nosotros vamos haciendo el php

**Comment by DamageESP** [comment]
Oka!

**Comment by NiciusB** [comment]
Jajaja ponte a hacer los prestamos bien :tongue:

**Comment by NiciusB** [comment]
Damage, si vas a cambiar los clanes, cambia solo el codigo necesario de clan2.php a clan.php, ya que hay cosas en clan.php que no hay en clan2.php
Gracias :)

**Comment by DamageESP** [comment]
De momento no voy a cambiar nada, solo lo estaba subiendo por si se me perdia o rompia algo xD

**Comment by NiciusB** [comment]
Ok jaja era por asegurarme :P
