### ISSUE TITLE
Misiones especiales

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#42]
Estaría bien hacer un apartado de misiones, donde salen diferentes tipos de misiones (de ataques, de compras, de clanes, de espionajes, de investigaciones....) con una duración determinada y vamos metiendo misiones de vez en cuando.
Ej:

**¡Defiende tu propiedad!**
-Gástate 5kk en entrenar personal
-Compra 6000 guardias
-construye 2 centros comerciales
-mete 2000 guardias en tu clan

_Si completas todos los requisitos, obtendrás un premio de:_
5kk de fichas
1kk de dinero para el fondo de investigaciones de tu clan
2000 de influencia
3000 saboteadores

¿Que os parece?
Así se le daría dinamismo al juego y alguna cosa mas para pasar rato en el juego xD

**Comment by Manuestaire** [comment]
Desafío semanal ????

No me parece mal, pero pienso que favorecen a la gente que está más avanzada en el juego, que los puede completar con más facilidad. Habría que pensar en una forma de ponerlo, de forma que sea más o menos igual de dificil para todos...

**Comment by DamageESP** [comment]
@Manuestaire Eso se podría hacer con una constante, que se multiplique por los ingresos de cada jugador o algo parecido. Estilo:

Gástate ($user_datos['ingresos']/10) € en entrenar personal.

**Comment by NiciusB** [comment]
Sep, en eso estaba pensando yo xD segun tus ingresos, o tus investigaciones, te pedirá mas o menos cosas

**Comment by Manuestaire** [comment]
Creo que estaría bien que hagamos esto, después de las subastas #37, así podríamos usar un formato parecido para los distintos tipos de desafíos, o poder regalar targetas como recompensa.

**Comment by NiciusB** [comment]
Me gusta xD pues eso, esperamos a hacer las subastas

**Comment by Manuestaire** [comment]
Había pensado, que ya que sería díficil vincular el logro diario a la dificultad propia de cada jugador, según su nivel, sería más práctico aplicar esto con misiones del tipo:
- Realiza 3 espionajes con éxito
- Consigue un botín de al menos 5000€ en un sabotaje
- Gana el bote en un Casino
