### ISSUE TITLE
Desglose de bonus

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#44]
Recupero también esta otra sugerencia que hice en los foros de MM:

> Actualmente en la pestaña de investigaciones del menú, el bonus de +1 de las alianzas por ejemplo, aparece ya sumado, la idea es que en vez de aparecer todo sumado aparezca desglosado con imágenes, una imágen para el bonus de la alianza:![](http://imagenes.megamagnate.net/megacorps/ali1.gif) ![](http://imagenes.megamagnate.net/megacorps/ali2.gif) ![](http://imagenes.megamagnate.net/megacorps/ali3.gif); otra imágen para los bonus de los líderes: ![](http://imagenes.megamagnate.net/lideres/h1h3.gif)![](http://imagenes.megamagnate.net/lideres/h2h3.gif), y otra para los powerups: ![](http://imagenes.megamagnate.net/powerups/pw1.gif) ![](http://imagenes.megamagnate.net/powerups/pw2.gif) ![](http://imagenes.megamagnate.net/powerups/pw3.gif)
> 
> En cualquier caso al final _adjunto una imagen_ para que se entienda mejor.
> :![](http://foro.megamagnate.net/download/file.php?id=384)

**Comment by NiciusB** [comment]
Lo haré a su debido tiempo xDD pero lo del líder no va a existir xD

**Comment by Manuestaire** [comment]
Ya digo que sólo lo he recuperadodel foro de MM, no he tocado el post original que hize...

**Comment by NiciusB** [comment]
Ok, pues a mi me parece bien y no es muy dificil

**Comment by NiciusB** [comment]
Añadido.
