### ISSUE TITLE
Finalización de ataques (Reportes animados)

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#45]
Se enviará un mensaje con datos simples (ganas/pierdes, tropas, edificios rotos, dinero...) y un link a una página donde sale la batalla por rondas semi-animadas con jquery (aparición de datos progresiva, etc)

**Comment by Manuestaire** [comment]
puedo recomendar que en lugar del link a otra página, el contenido se cargue vía ajax en un cuadro de diálogo de Jquerry?? http://jqueryui.com/dialog/#modal-message

**Comment by NiciusB** [comment]
Está bien, me parece que con el dialogo quedaría mejor sisi

**Comment by NiciusB** [comment]
Tabla creada y funcionando (u_rondas).
En los mensajes se enlaza http://megacorporation.conpingo.com/visor.php?a=218 (con el id del ataque)
Aún falta hacer esta página. Le he puesto algo de seguridad y una prueba para mostrar todo :D

**Comment by NiciusB** [comment]
El visor ya se ve en una tab.
Ya se hay una prueba para el diseño y la muestra de rondas funcionando.
Ideas para cambiarla aqui :D

Hay un problema menor que no es muy importante: Si abres una batalla y antes de que termine (duran como 10 segundos o menos) abres otra, las tropas mezclarán datos de las dos batallas xD

**Comment by NiciusB** [comment]
El visor ya está funcionando en version pre-alpha xD faltan estilos y posiblemente cambios de funcionamiento, pero la idea está hecha y funcionando.
Aportad ideas o cambiadlo a gusto :D

PD: Necesito textos para los comentarios!!
PD2: La estructura sería mas o menos así:
           - Textos para si no muere nadie en la ronda de los defensores
           - Textos para si no muere nadie en la ronda de los atacantes
           - 4 tipos de textos para si mueren mas tropas de cada tipo (Con posibilidad de limitar tropas máximas y mínimas)

Podeis hacer sugerencias para mas tipos de textos

**Comment by Manuestaire** [comment]
Pongo varias frases para que veas como las quieres meter.
- Los atacantes consiguen burlar la defensa de la corporación en enemiga y completar la misión sin ser descubiertos.
- Los atacantes fueron descubiertos y neutralizados sin problemas.

**Comment by NiciusB** [comment]
Los dos mensajes han sido implantados, aparecen siempre sobreescribiendo al comentario de la última ronda

**Comment by NiciusB** [comment]
Venga, manuel, necesito un diseño bonito para el visor de ataques :)

**Comment by Manuestaire** [comment]
el viernes termino los exámenes así que de momento ando liado

**Comment by NiciusB** [comment]
Ok xD a ver si tenemos mas actividad, que cada dia que pasa mas gente pierde la esperanza en MM xD

**Comment by Manuestaire** [comment]
al final esto entra en la a-0.1.2 ¿????

**Comment by NiciusB** [comment]
Pues en teoría asi, a ver si me pongo este finde o algún día hasta el lunes jaja pero los examenes hacen mucho daño

**Comment by Manuestaire** [comment]
Retrasado a la  Alpha - a-0.1.3
