### ISSUE TITLE
Comprar varios edificios

### ISSUE THREAD

**Issue by DamageESP** [Manuestaire/megacorporation#46]
Sigue cobrando mal... he probado a crear varias cuentas y comprar estancos, en cada cuenta me permitia comprar una cantidad distinta.

@NiciusB

**Comment by Manuestaire** [comment]
No se puede hacer que para comprar se usa un for, que itera el número de veces, que edificios quieres comprar?

**Comment by NiciusB** [comment]
Cada cuenta te permitía comprar cantidades distintas con 100k € todas?
Pero eso es imposible xDD :/ veré si hay algo mal jaja

**Comment by NiciusB** [comment]
Ya te cobra bien... ahora falta que el dinero que te dice que cuesta al comprar varios sin recargar la pagina esta mal

**Comment by NiciusB** [comment]
Arreglado

**Comment by DamageESP** [comment]
Hay otro bug: 

Tengo 10kk e intento comprar dos edificios, cuyo valor total es superior a 10kk, pero si pongo esto: 1.55 me deja comprar dos edificios al precio de uno.

Carrefour 2x1 jajaajja

**Comment by Manuestaire** [comment]
jajajaja, hay que requerir integers en todos los imputs de ese estilo...

**Comment by DamageESP** [comment]
LoL @NiciusB sales en un screenshot de zombipolis, mira el ultimo, de esos que hay en el index xD

**Comment by NiciusB** [comment]
Jajajaja y lo pones aquí? xDDD
No se yo si debería sentirme halagado....
http://imagenes.zombipolis.com/screen/screen6.gif

**Comment by NiciusB** [comment]
arreglado xDD
