### ISSUE TITLE
Donaciones voluntarias (Dinero real)

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#49]
Se puede hacer un apartado de donaciones voluntarias, que no dan ningún tipo de beneficio en el juego.
Así se puede destinar lo que den a mantener el servidor o conseguir un servidor dedicado para megacorporation

**Comment by DamageESP** [comment]
Me parece bien, y pasado un tiempo, si vemos que no hay problemas con MM y eso, se podrían poner servicio premium, por ejemplo La compra multiple de edificios y las actuales ventajas.

**Comment by NiciusB** [comment]
Bueno, una recompensa de fama podría ser, pero no estoy de acuerdo con ofrecer servicios premium
Al fin y al cabo, hemos hecho este juego en parte para acabar con los visa players, no?

**Comment by DamageESP** [comment]
A ver, no compares ofrecer saboteadores gratis como hicieron esta gente con algunas opciones para comprar edificios mas comodamente como estoy diciendo yo, quiero decir, si se pone premium, las ventajas que tendrian serian puramente para ahorrar trabajo tedioso, pero no para ponerle por las nubes como hacen en MM. Yo me refiero a lo de poner compra multiple de edificios (ahorraria tiempo, sobre todo para la gente con internet lento), el asistente de casinos (ahorraria tener que ponerse el autoclick, o en su defecto, tener que programar uno como el tuyo), las misiones express (ahorra tiempo), y otras que se nos ocurran, pero obviamente sin dar tantas ventajas como en MM. Los ataques extra no estarian a la venta y tampoco se podria comprar fama.

Tambien es verdad que si se hiciera esto, habria que rebajar las recompensas por logros y todo, asi que no se, como querais. A mi me da lo mismo, yo esto lo hago por diversión, pero si además te puedes ganar unas perras...

Que opinais? Cito a @Manuestaire para que le salga en novedades.

**Comment by NiciusB** [comment]
Desde el principio la idea era hacerlo sin ánimo de lucro, lo de donaciones lo dije para mantener el servidor y conseguirnos uno dedicado a megacorporation (y ya de paso, no sobrecargar el mio xD), no pensaba en ganar dinero nosotros.

Otra cosa es lo de compra multiple, yo creo que debería ser para todos para siempre, no tiene sentido que teniendo esta mejora no se aplicara a todos, ya que lo único que haría sería joder al personal, y darle mas carga al servidor. Es diferente el asistente para casinos, ya que eso si que es totalmente automático y prescindible, no es un "derecho básico".

**Comment by DamageESP** [comment]
Lo que has dicho me parece bien, pero seamos realistas, quien va a donar a un juego en el que todo es gratuito? A la gente le da igual que la url sea subdominio de conpingo o sea un dominio independiente, y tampoco le importa que se sobrecargue el dedicado. No sé, pienso que para que la gente done tiene que obtener algo a cambio, aunque sea un reconocimiento, un emblema, ALGO xD si no no creo que se anime nadie.

Excepto los de siempre, puede ser...

**Comment by NiciusB** [comment]
De hecho la idea me la dio uno en el chat de msn de MM xD

**Comment by Manuestaire** [comment]
Yo lo daba por hecho, quiero decir, creía que era obvio que íbamos a aceptar donaciones para pagar el hosting.

**Comment by DamageESP** [comment]
Por cierto, alguien sabe como va eso? Paypal supongo no?

**Comment by NiciusB** [comment]
Sep, es la forma más fácil y mas rápida.
Además, como es simplemente de donación, no hace falta comprobar nada, simplemente ponemos el boton de donar xD

**Comment by Manuestaire** [comment]
La cuenta de paypal y todo eso lo gestionas tu nuno? 

Lo digo porque lo que tengo pensado es que en el perfil.php o en el header, para que salga en todas las páginas, meter en un div flotante este widget: https://giving.paypallabs.com/authenticate/review 
Y que se pueda ocultar con un botoncillo discreto, que se recuerda en una cookie. Es un script que tengo por ahí y que solo le falla la función para intentar eliminar la cookie.

**Comment by DamageESP** [comment]
Veo bien tener una cuenta compartida, y con el dinero que haya decidimos entre todos lo que hacer con ese dinero. Supongo que lo primero es un dominio y un dedicado, y luego comprar algunos iconos como el que me enseño Manu no estaria nada mal. El widget que has puesto esta muy bien, pero no veo la necesidad de borrarlo, que esté ahi siempre, no?

**Comment by Manuestaire** [comment]
Si se pone flotante, puede molestar, de ahí lo que se pueda ocultar y quede en una cookie, si consigo acoplarla a un sitio donde no estorbe si que se podría poner normal.

**Comment by NiciusB** [comment]
He puesto una prueba en el juego.
Supongo que si que es molesta... habría que buscarle un sitio en el nuevo diseño

**Comment by NiciusB** [comment]
Ahora que hemos decidido poner en el juego un banner, no creo que esto sea necesario como para ponerlo en todas las paginas. Propongo ponerlo solo en el perfil o borrarlo

**Comment by Manuestaire** [comment]
Para la alpha veo bien poner el banner, pero tal y como está el juego poner el banner en la beta o en la versión abierta que sea a mí me parece meterse en líos poner el banner sin cambiar más cosas.

**Comment by NiciusB** [comment]
Me parece bien. Aunque supongo que en la Beta o la V1 el juego estará más cambiado de lo que está xD

**Comment by NiciusB** [comment]
Añadido botón de cerrar, que se guarda por 24 horas (le pongo mas tiempo?)

**Comment by DamageESP** [comment]
Nono asi esta bien
