### ISSUE TITLE
Dinero repartido cada segundo.

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#50]
He pensado un sistema para repartir el dinero instantáneamente, sin tener que esperar un minuto.
La cosa es: en la bd hay un campo con un número de tiempo unix.
Al hacer una carga de cualquier página, se compara el tiempo unix actual con el de la base de datos. Si es mayor, se calcula el numero de segundos que han pasado y se reparte el dinero, también se cambia el numero de la base de datos.

¿Que os parece?

**Comment by DamageESP** [comment]
No sé que es un numero de tiempo unix, pero suena bien xD

Prueba, y si no pues se pone como antes.

**Comment by NiciusB** [comment]
Terminado
