### ISSUE TITLE
BUGs

### ISSUE THREAD

**Issue by DamageESP** [Manuestaire/megacorporation#52]
Hago este issue para que pongamos aqui todos los bugs y no tengamos que estar creando nuveos issues.
- Nadap

P.D.: Editad este mensaje para añadir o quitar bugs, es decir, no contesteis a no ser que sea para decir otra cosa. Asi los tendremos mas organizados.

**Comment by NiciusB** [comment]
Lo de las tropas de los clanes creo que funciona... al menos a mi xD

**Comment by DamageESP** [comment]
Pues yo me acabo de crear un clan, he puesto en todo 99999 y no me deja sacar ni uno. Y he recargado los permisos.

**Comment by NiciusB** [comment]
que te dice?

**Comment by DamageESP** [comment]
No puedes sacar mas recursos de este tipo hoy

**Comment by NiciusB** [comment]
Te has puesto el rango y le has dado a regenerar permisos después de eso, al tener el rango con permisos dado?

**Comment by DamageESP** [comment]
Si

**Comment by NiciusB** [comment]
Bien, puedes sacar 99999999 de dinero, pero de lo demás no porque tu rango no tiene esos permisos xD solo deja sacar dinero

**Comment by DamageESP** [comment]
Por que? Si puedo sacar supuestamente 9999999 de todo?

**Comment by NiciusB** [comment]
En la base de datos he mirado tu rango y solo pone 999999 de dinero, el resto está a 0 xD

**Comment by DamageESP** [comment]
Pues no se guardara bien :/

http://gyazo.com/fdbb6c02274b9f6893624fcc233ace42.png

**Comment by Manuestaire** [comment]
Os dejo por aquí eso: http://www.tinymce.com/wiki.php/Configuration:theme_advanced_font_sizes

**Comment by NiciusB** [comment]
LOL tienes el rango Admin, no el Admin2... y el Admin es el que solo tiene dineero xD

Manu, para que queremos eso? xDD

**Comment by Manuestaire** [comment]
Para esto que comentaba dmg: En los perfiles de los clanes, puedes poner una descripción lo grande que quieras, no hay limite de caracteres. Propongo habilitar solo cambiar el texto de color y ponerlo en negrita, cursiva y esas cosas. Lo basico vaya, y poner un limite de 600 caracteres por ejemplo.

**Comment by DamageESP** [comment]
Ya he probado he puesto rango Admin2, he recargado permisos y me sigue sin dejar. Algo fallaa!!! xD

**Comment by NiciusB** [comment]
Yo digo un limite de 6000 caracteres xD

**Comment by Manuestaire** [comment]
Yo creo que lo de limitar el tamaño de fuente es necesario, 6000 caracteres al tamaño máximo de letra, son dos horas haciendo scroll...

**Comment by DamageESP** [comment]
Lo que se debería permitir en las descripciones en mi opinion es: negrita, cursiva, subrayado, colores, tamaño maximo 14pt, extension maxima 1000 caracteres.

**Comment by NiciusB** [comment]
O si no se puede meter en un div con overflow:auto; y un height de 500 pixeles

**Comment by DamageESP** [comment]
También, pero en ese caso me gustaria poner una barra de scroll personalizada, me gusta la que hay en el index de conpingo.

**Comment by NiciusB** [comment]
jaja pues ya sabes xD
http://css-tricks.com/custom-scrollbars-in-webkit/

**Comment by DamageESP** [comment]
Lo malo es que según veo solo sirve para chrome no?

**Comment by NiciusB** [comment]
Ah lol es verdad xD y para safari tambien jajaja...
pues busca otros, nuse xD

**Comment by Manuestaire** [comment]
Una vez más jqerry tiene la solución: http://jqueryui.com/slider/#side-scroll

**Comment by DamageESP** [comment]
Actualizado

**Comment by Manuestaire** [comment]
Como no sabía dónde ponerlo lo digo por aquí habría que poner que en concepto de mantenimiento del déposito, si tienes más de 10.000 Fichas en el Casino te cobran un 4% de interés. Así se evita excesiva acumulación de dinero en casinos, y podemos pensar en hacer más cosas con el dinero en la cuenta corriente.

**Comment by NiciusB** [comment]
Me parece muy bien, algo como impuestos semanales de fichas o algo asi xD

**Comment by Manuestaire** [comment]
Lo pongo aquí, que creo que así se agrupa mejor:

Hay un problema con el registro, si escribes un nombre que no está disponible no te lo dice hasta que no has completado todos los pasos del registro. Además el código de invitación se queda usado al parecer. Lo ideal sería que al lado del mismo campo del nombre salga si está o no disponible como en muchas páginas.

**Comment by NiciusB** [comment]
El código solamente se usa cuando te registras correctamente. Miraremos como hacer lo de la comprobación automática, será parecido al search-in.php del ranking, supongo

**Comment by DamageESP** [comment]
Listo lo de la disponibilidad del nick.

**Comment by NiciusB** [comment]
Bien jaja pues lo del código que se cancela también lo arreglé

**Comment by DamageESP** [comment]
El que es eso nuno? Hay que poner para que te salgan bien los beneficios en la barra de estadisticas.
Por cierto, ya va bien lo del dinero cada segundo, antes iba hacia atrás.

**Comment by NiciusB** [comment]
Yap jaja estuve arreglando eso y los préstamos ayer
¿Cual es el problema con los beneficios?

**Comment by DamageESP** [comment]
Que no te muestra lo que ganas realmente, ahora mismo yo tengo 1millon de sabots y me sale como si no pagara ni impuestos ni mantenimiento.

**Comment by NiciusB** [comment]
Ya funcionan bien :dancers:

**Comment by DamageESP** [comment]
Actualizado

**Comment by Manuestaire** [comment]
Sabotajess [ 22:02 ]  
dmg[XIII] realiza un ataque con ¡Exito! +512 Fama

Y esas dos ss?

**Comment by NiciusB** [comment]
Estas 2 s son una prueba mía porque no se estaban borrando correctamente las novedades viejas. Ya funciona todo correctamente.

**Comment by DamageESP** [comment]
Actualizado

**Comment by NiciusB** [comment]
Si alguien me dice como son las formulas para los impuestos los arreglo.

**Comment by DamageESP** [comment]
Pues a partir de los 10kk de ingresos pagas un 3% de impuestos, y cada 10kk que subas, te aumenta un 1% los impuestos

**Comment by Manuestaire** [comment]
10kk es 10M ?

**Comment by NiciusB** [comment]
Entonces es normal que tengas un 55% de impuestos, ya que tenemos unos ingresos desorbitados

**Comment by Manuestaire** [comment]
Me pregunto que pinta tendrá el pie chart de las finanzas, si tienes más gastos que ingresos :S

**Comment by DamageESP** [comment]
Así

http://gyazo.com/7551bb757567aaa5a174249aee794cc7

**Comment by Manuestaire** [comment]
Vale, me refería a si tienes pérdidas, es decir beneficios negativos. (sólo se me ocurre que gastes más en tropas de lo que ingresas)

**Comment by DamageESP** [comment]
Da un error que dice: "Pie Chart does not allow negative values" o algo así

**Comment by NiciusB** [comment]
Sep, lo daba con los préstamos...
Con lo de las tropas tenemos que pensar algo como despido gratis de todas las tropas (no vale solo unas cuantas) o algo asi... porque sin dinero no puedes despedir :S

**Comment by NiciusB** [comment]
Bueno, si el bug de impuestos no es un bug, y los logros vamos a cambiarlos... creo que está todo terminado, no?

**Comment by Manuestaire** [comment]
@DamageESP Da un error que dice: "Pie Chart does not allow negative values" o algo así

Para evitar ese bug, hay que poner un condicional, si se da la condición se genera un gráfico distinto y punto, uno de barras por ejemplo que muestre que gastas más de lo que ingresas y punto.

**Comment by Manuestaire** [comment]
Lo de los límites a los caracteres y a las funciones de la descripción de los clanes se hizo?

**Comment by NiciusB** [comment]
Ya se hizo, si.
La desc. de los clanes tiene un limite de 600 caracteres

**Comment by DamageESP** [comment]
Actualizado.

**Comment by NiciusB** [comment]
Actualizado.

**Comment by DamageESP** [comment]
Actualizado

**Comment by NiciusB** [comment]
A que te refieres con "automáticamente se refresca"?
Que yo sepa, criminales.php no se actualiza automáticamente, y he mirado el código por encima y no he visto tampoco ningun javascript o algo...

**Comment by DamageESP** [comment]
Pues no me preguntes por que pero solo el Firefox cada vez que intento entrar se me pone a refrescar automaticamente la pagina infinitas veces, pero en chrome no. Podeis probar en firefox a ver si soy el único?

**Comment by NiciusB** [comment]
Pues a mi en firefox me va perfectamente, hamijo

**Comment by NiciusB** [comment]
Damage, te sigue sin cargar criminales.php?

**Comment by DamageESP** [comment]
Sí, se sigue autoactualizando

**Comment by NiciusB** [comment]
Prueba a mirar con ¿firebug? a ver si encuentras alguna pista :P

**Comment by DamageESP** [comment]
Que se supone que hace eso? xD

**Comment by DamageESP** [comment]
Updated.

**Comment by NiciusB** [comment]
Actualizado

**Comment by Manuestaire** [comment]
actualizado
 Si no me equivoco, que puede ser que si, para calcular lo que habría que restar cada segundo sería:
(Fichas \* %Interés) / (24_60_60)

**Comment by DamageESP** [comment]
Añadido pequeño bug

**Comment by Manuestaire** [comment]
Cierro este issue, para darlo por concluido para la alpha

**Comment by DamageESP** [comment]
Actualizado!

**Comment by Manuestaire** [comment]
Ok, pero las cosas de clanes no están pensadas para esta versión...

Yo creo que ya mejor abrir otro hilo de bugs para la alpha-0.2.0

**Comment by NiciusB** [comment]
Arreglado y actualizado
