### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#56]
El hosting de conpingo no será para siempre.
O nos vamos a uno gratis o pagamos uno. Yo digo de quedarnos en este hasta la Beta o así, y si tenemos dinero pagarnos uno.  Conozco a uno en eRepublik con el que hablo casi todos los días y tiene un hosting web muy barato. No es tremendamente bueno, pero podemos mirarlo xD ¿Que decís?

300mb de espacio y 3gb de trans. 6 euros al año
500mb de espacio y 5gb de transf.  17 euros al año
1 gb de espacio y 12 gb de transferencia mensual 24 euros al año
3gb de espacio y 35 gb de transferencia 48 € al año
5gb de espacio y 60gb de transf. 72 al año

**Comment by Manuestaire** [comment]
Lo de la transferencia limitada es un asco, si te lo quitas de en medio te olvidas de muchas preocupaciones, así que yo recomendaría cualquiera con transferencia ilimitada.

**Comment by NiciusB** [comment]
Bueno, si conseguimos pagarnos uno sin tener que poner anuncios por mi bien xD la cosa es eso xD

**Comment by Manuestaire** [comment]
http://www.1and1.es/hosting-linux?__lf=Static&linkOrigin=&linkId=hd.subnav.linuxhosting

http://www.axarnet.es/hosting/hosting-linux.php

**Comment by NiciusB** [comment]
Me gusta el Hosting Ocio de axarnet. Es el mas equilibrado y barato. En su defecto el Dual Avanzado de 1&1 no está nada mal...

**Comment by Manuestaire** [comment]
El de 1&1 serían unos 30€, porque los 6 primeros meses son gratis.
El de Axarnet 47,70€ .

Ventajas de axarnet, bases de datos ilimitadas, por el resto de cosas hay poca información.
Pero 1&1 da 100Gb en vez de 10Gb. Sólo 10db y 10 cuentas ftp y 100 cuentas de correo a 2Gb por buzon, en axarnet son ilimitadas pero de 1Gb cada.

**Comment by NiciusB** [comment]
Las cuentas de correo dan exactamente igual, y las 10 db y ftp nos la sudan, con tener 2 o 3 nos sobra xDD
Lo del espacio si que está bien...
Otra cosa es el nombre de dominio que nos regalan... ¿Cual cogeríamos? www.megacorporation.com ya está utilizado se puede hacer .es, .org o con otro nombre

**Comment by NiciusB** [comment]
http://www.strato-hosting.co.uk/hosting/ es el que usan Berto & company... no me parece muy bueno xD

http://www.hostinger.es/hosting-web es otro que no parece malo

**Comment by Manuestaire** [comment]
http://www.strato-hosting.co.uk/hosting/ no tiene php5 en el primer plan así que yo lo descartaría.

El otro, no me inspira confianza el plan gratuito pero bueno, todo es probar.

**Comment by DamageESP** [comment]
El de axarnet parece muy completo, pero recordad que no podemos contratar algo que luego no podamos pagar. En mi opinion no seria mala idea poner publicidad para asegurarnos unos ingresos minimos.

**Comment by Manuestaire** [comment]
Yo tiraría por 1&1 que a la larga es el más barato, o probar el plan gratuito de hostinger

**Comment by NiciusB** [comment]
Para la versión Alpha, podemos estar en el de conpingo... yo me refería a un plazo mas largo como la Beta abierta o la versión 1

**Comment by DamageESP** [comment]
El dual avanzado de 1&1 está de puta madre, además son los 6 primeros meses gratis (el primer mes hay que pagar el alta, que son 6,04€), y luego 6,04€ al mes, con un contrato de permanencia de 12 meses. Lo veo bastante viable, que opinais?

De todas formas antes de contratar lo suyo es llamar y enterarse bien de los IVAs, el soporte técnico y esas cosillas.

**Comment by NiciusB** [comment]
contratando eso nos darían dos .com .es .info .name .net .org .biz .eu .com.es .org.es habría que ver cuales coger.
Por lo demás me parcee todo bien, la única pega el máximo de 5 bases de datos mysql

**Comment by DamageESP** [comment]
.es y .net
Lo de las BD, para que quieres más de 5?

**Comment by NiciusB** [comment]
Nah, solo comentaba xD
A mi me sale:
alta - 4,99 €
coste - 0,00 € los 6 primeros meses, después 4,99 € al mes
Compromiso mínimo de permanencia de 12 meses.
megacorporation.es y .net? no me parece mal, pero igual seria mejor buscar otro nombre o otro nombre de dominio

**Comment by DamageESP** [comment]
Letra pequeña !! 

Importe total de la primera factura: 6,04 € = Base imponible: 4,99 € + IVA (21%*): 1,05 €

megacorporation.es esta disponible pero el .net no D:

**Comment by NiciusB** [comment]
Ah jajajaja he caido como un tonto xDD
Calculo que con 20.000 impresiones al mes (no es muy dificil...) y un banner no muy grande ni molesto podríamos ganar mas o menos 6€ al mes...
He aqui nuestras estadisticas:

Mes /   /  Impresiones
Sep 2012 /  / 30,854
Oct 2012 /  / 9,579
Nov 2012 /  / 5,365
Dic 2012 /  / 9,138
Ene 2013 /  / 6,111

Eso es con 3 usuarios (Obviamente, hacemos mas impresiones que un usuario normal). Con 100 usuarios haríamos las 20k impresiones, calculo yo

**Comment by DamageESP** [comment]
Bueno pues yo no se mucho de trafico ni nada, pero supongo que son visitas únicas, no? O son hits? Megaapps tiene 300 visitas de media y no lo usa casi nadie...

**Comment by DamageESP** [comment]
He estado leyendo opiniones sobre gente que ha estado con 1&1 y no opinan demasiado bien...

http://www.burbuja.info/inmobiliaria/emprendedores/297450-que-os-parece-1-and-1-mi-web-2.html
http://blog.ideasalcubo.net/312_11-Mi-Web-al-descubierto.html

Por otro lado Strato tambien tiene buenas ofertas (Hosting Avanzado por 3,99€+IVA):

http://www.strato.es/hosting/paquetes/

Habría que leer opiniones sobre esta

**Comment by Manuestaire** [comment]
Lo de 1&1 mi web, no nos afecta, lo que me preocupa s lo de los dominios,

**Comment by NiciusB** [comment]
Los comentarios de 1&1 son sobre hacer la página con el diseñador de páginas para empresas y eso... eso no nos afectaría.
Lo que si que tienen razón es que sus servidores están en Alemania... estaría bien encontrar algún hosting bueno y barato en España

**Comment by DamageESP** [comment]
Página españolas de hosting recomendados:

www.cdmon.com
www.dinahosting.com
www.espanahosting.com <- OJO al plan "Ilimitado+" de 5,95€(supongo que +IVA). Lo unico malo que veo es que creo que hay que contratar 12 meses obligatoriamente.

**Comment by NiciusB** [comment]
El mejor me parece España Hosting. En el plan Ilimitado+ (12 meses) nos cobrarían
Subtotal    71.40 €
IVA (21.00%)    14.99 €
Total   86.39 € (7,199€/mes)
Demo del panel de control: https://plesk11-power.demo.parallels.com:8443/login_up.php3?login_name=admin&passwd=panel&login_locale=en-US (Es el mismo que usan en MM)

**Comment by DamageESP** [comment]
Pues el de España Hosting tiene muy buena pinta. Lo único que eso, hay que estar un año nos guste o no, podamos pagarlo o no.

**Comment by NiciusB** [comment]
España Hosting
Buenas tardes
Tiene un periodo de 30 días en los que si no queda satisfecho le devolvemos su dinero.

**Comment by DamageESP** [comment]
Ah ps perfect.

**Comment by Manuestaire** [comment]
No sé si lo habeís tenido en cuenta, pero si al final el servidor no está en españa es posible que haya que ajustar la hora.

**Comment by DamageESP** [comment]
A que te refieres? Ya ajustamos la hora en la version actual para que sea hora española.

**Comment by NiciusB** [comment]
De hecho el de ahora los crons de por ejemplo el sabado los tiene a otra hora para que aqui sean las 00:00 xDD
De todas formas, el hosting de santiago al final es mas caro (sobre 6€ al mes) asi que supongo que contrataremos el de España Hosting

**Comment by Manuestaire** [comment]
@DamageESP  ok ok a eso me refería..

**Comment by NiciusB** [comment]
Reabriremos cuando este tema sea otra vez importante y necesario
