### ISSUE TITLE
Rankings [Diseño]

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#57]
Próximo paso, el diseño de los rankings.

He aquí el modelo que quiero seguir: http://img.photobucket.com/albums/v111/fedek_kurga/RankInvest.jpg
Por supuesto cambiando colores y cosas

A lo que voy, sería posible hacer lo de los puestos del rank, es decir, cuantos puestos has subido o bajado del día anterior a este? Porque en intervalos de media hora, el cambio será mínimo.
@NiciusB @DamageESP

**Comment by NiciusB** [comment]
Se puede hacer. Me pondré con ello hoy o mañana

**Comment by Manuestaire** [comment]
@NiciusB no tengo especial prisa, pero por favor que no se olvide esto.

**Comment by NiciusB** [comment]
En el ranking de usuarios ya muestra las diferencias del actual con el de esta mañana a las 00:00

**Comment by Manuestaire** [comment]
Ayer, ya incluí los chars para que quede más bonito si has subido o has bajado.

Una pregunta, cómo puedo cambiar por separado los estilos del nombre de usuario y los del tag del clan?? ¿Se está cargando todo junto verdad?

**Comment by DamageESP** [comment]
Crea una clase para .nick y otra para .clan, yo me encargo de que tengan esa clase.

**Comment by DamageESP** [comment]
He creado un par de estilos para las tablas para cada uno de los themes en http://megacorporation.conpingo.com/tablas/ decidme si os molan o no.

**Comment by NiciusB** [comment]
Si, bueno, no están mal... pero son como muy cuadrados, no? xD
Ese degradado azul es raro, no sé jaja me da sensación de ser como de los años 2000 jaja

**Comment by NiciusB** [comment]
Bueno... ya está terminado, no?

**Comment by Manuestaire** [comment]
No, aquí faltan cosas

**Comment by NiciusB** [comment]
Como cuales? jajaja

**Comment by Manuestaire** [comment]
Cosas de estilos, don't worry.

Lo del autocomplete de búsqueda qué paso al final?

**Comment by DamageESP** [comment]
Queda por hacer.

**Comment by NiciusB** [comment]
Vamos, vagos... dadle a los estilos caña jeje

**Comment by NiciusB** [comment]
Hola... que falta aqui?

**Comment by Manuestaire** [comment]
Pues lo mismo que faltaba antes, pero vamos tranquilo que se hace en cualquier momento, preocupaós de tener gente para la alpha.

**Comment by DamageESP** [comment]
Cierro, incluimos estas cosas en Changelog
