### ISSUE TITLE
Nuevo Diseño

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#58]
Parece que aquí todo el mundo estaba pensando en un nuevo diseño pero nadie tiene nada hecho xD
He dibujado uno que básicamente es como el actual pero a mi parecer mas bonito... Los colores serían Gris/Blanco/Azul y un fondo de un skyline con un degradado a negro en caso de scroll hacia abajo.
Voy a ir haciéndolo en un directorio en 2 htmls, un ejemplo de página y el login.
Podéis verlo en http://megacorporation.conpingo.com/d/

Proponed ideas o imágenes.

**Comment by Manuestaire** [comment]
Teneís una manía por los colores oscuros...

De todas formas, ya que no nos ponemos deacuerdo con el diseño, por qué no hacemos varios skins?

Al usuario se le deja elegir un skin y la ruta de las imágenes y el css dependen del skin elegido.

**Comment by DamageESP** [comment]
Recordad que tengo mi diseño ahi !

**Comment by NiciusB** [comment]
La idea de manuel me parece PERFECTA. Es una muy buena idea :D podemos hacer también concursos de skins y las metemos al juego. Me encanta :D

**Comment by NiciusB** [comment]
Implementado el sistema de diferentes estilos. De momento aún no tiene forma de elegir el estilo (es el default a todos menos al id 5: $themename="default"; if($user_datos['id']==5)$themename="skyline";)

Los estilos están en:
PHP y HTML (cabecera, footer y estadisticas.php): /includes/themes/nombre
CSS (common.css): /css/nombre
IMAGENES: /imagenes/nombre (De momento solo hay 3 imágenes del tema skyline)

**Comment by Manuestaire** [comment]
y no hubiese sido mejor que las carpetas fuesen las de los themes, y dentro css, images etc...

más que nada se suele hacer así para evitar tener que ir cambiando de carpetas todo el rato en el ftp

**Comment by NiciusB** [comment]
Todo cambiado a /themes/nombre (php, css y imagenes)

**Comment by NiciusB** [comment]
Ya puedes elegir el tema editando tu perfil.
La lista de temas está en el archivo de /constantes_juego.php en un array
