### ISSUE TITLE
Recuperar Contraseña

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#59]
Hay que hacer la página para recuperar contraseña al e-mail.

Importante que no se envie la contraseña original si no que se mande un link para introducir o generar una nueva...

**Comment by NiciusB** [comment]
Creo que funciona correctamente.
Si encontráis cualquier bug, avisadme. Si no, cerramos.

**Comment by NiciusB** [comment]
Pues como nadie dice nada y a mi me parece que está bien, cierro.
