### ISSUE TITLE
Opciones del Perfil

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#60]
Hay que añadir las opciones de Perfil.
- Cambiar contraseña
- Cambiar e-mail (el original hay que guardarlo para evitar robos de cuenta)

**Comment by NiciusB** [comment]
Añadidas las dos opciones.
Me gustaría saber cómo es lo de que se guarde el email original... para eso no dejamos cambiar el email xD

**Comment by DamageESP** [comment]
No me parece bien poder cambiar el email, ya que favorece uso de multis. Con una confirmacion de correo seria suficiente.

**Comment by NiciusB** [comment]
Lo de las multis es una paranoia, sinceramente xD
Podemos hacer que cada vez que se cambie de email se envíe un correo a la cuenta original y a la cuenta de antes de cambiarlo, en caso de ser diferentes.

**Comment by Manuestaire** [comment]
@NiciusB Lo interesante sería que el e-mail con el que te registraste se guarde siempre. Así si a alguien le roban la cuenta, esta se puede recuperar con el e-mail original y la intervención de un admin.

Lo del correo de registro ahora mismo cómo está? Hay que confirmar el registro?

**Comment by DamageESP** [comment]
Ahora mismo no, pero de momento para la alpha no es necesario, ya que se accedera por invitacion. Hay que incluirlo en la lista del ToDoH.

**Comment by DamageESP** [comment]
Oye, quien ha puesto esa H ahí xDD
Molaría una página de perfil que sirviera para algo y no solo te dijera tu fecha de registro y tus fichas.. xD

**Comment by NiciusB** [comment]
yo no he sido... :trollface:

A que te refieres con que sirviera de algo? Ahí irán las gráficas y tal, no?

**Comment by DamageESP** [comment]
Molaría que hubiese un montonazo de estadísticas, como puestos perdidos/ganados, proporción ataques recibidos/hechos, estampadas hechas/recibidas etc

**Comment by NiciusB** [comment]
Así la gente se entretendría mirándolas xD la cosa es hacerlas jajaja

**Comment by DamageESP** [comment]
Ya.. xD

**Comment by Manuestaire** [comment]
Esto está terminado? Cómo se ha dejado lo del cambio de e-mail? Se guarda el de registro?

**Comment by NiciusB** [comment]
Pues... el email cambia pero no guarda ná xD ni envia correos

**Comment by NiciusB** [comment]
Ya se guarda el email de registro. Cierro

**Comment by Manuestaire** [comment]
Habría que cambiar lo de que necesites meter la contraseña para cambiar el theme, o ya está cambiado?

**Comment by NiciusB** [comment]
Ya no te pide contraseña para cambiar el tema
