### ISSUE TITLE
Costes de mantenimiento de fichas

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#61]
Hay que añadir los costes de mantenimiento de fichas (si se tienen más de 10.000 Fichas, se cobra un 4% de interés diario). Estos 2 parámetros meterlos como variables, para poderlo ajustar.

**Comment by NiciusB** [comment]
Espera, esto es para los casinos o para las fichas de los usuarios?
Si son para usuarios ya está hecho y hay que cerrar

**Comment by Manuestaire** [comment]
Para las fichas de los usuarios, cuándo se hizo?

**Comment by NiciusB** [comment]
Pues hoy xD justo antes de comentar eso xD
