### ISSUE TITLE
LA DIFERENCIA

### ISSUE THREAD

**Issue by DamageESP** [Manuestaire/megacorporation#62]
Sigo pensando que se parece demasiado a MM. Tiene que haber un detalle que marque la diferencia con respecto a MM. Tenemos que pensar algo original y que tenga mucha importancia en el juego. Quizás una nueva moneda, una nueva sección, pero algo hay que inventarse.

**Comment by Manuestaire** [comment]
El sistema de ataque ya está completamente cambiado, y habría que darle más protagonismo.

Aparte sobre un árbol de tecnologías con la que ir desbloqueando nuevos edificios, opciones (préstamos, bolsa...), unidades. Qué opinaís?

**Comment by DamageESP** [comment]
Que los edificios se vayan desbloqueando poco a poco me parece una buena idea, con una nueva sección llamada "Tecnología", y que se divida en varias secciones, como por ejemplo: Pequeños negocios, PYMEs, etc y dentro de cada categoría se pueda upgradear cada edificio individualmente, cuyo efecto sea un pequeño "Optimizar Negocio".

**Comment by NiciusB** [comment]
Como lo de entrenar unidades en concreto (Por ejemplo, gangsters) pero con los edificios... :megusta:
Pero lo de la tecnología tampoco hacerlo muy grande, para no bloquear todo a los nuevos y que se aburran xD
La diferencia obvia es la que ya sabemos, no buscamos ganarle beneficios. Además actualizaremos constantemente, banearemos multis, habrá GOs, consideraremos realmente las propuestas, no habrá forma de pagar para ser mejor... Pero tienes razón, podemos buscar una diferencia aparte del posible poker, de los nuevos ataques, de las nuevas investigaciones, de poder elegir el tema que prefieras...

**Comment by Manuestaire** [comment]
A ver que os parece:
- Panadería, PUB y Farmacia, desbloqueados desde el principio.
- Gimnasio y teatro: 
  - Cuenta corriente (nivel 1)
  - Optimizar negocios (nivel 3)
  - Infraestructura (nivel 2)
- Concesionario y Banco
  - Cuenta corriente (nivel 4)
  - Optimizar negocios (nivel 4)
  - Infraestructura (nivel 2)
- Gasolinera, Hotel Resort.
  - Cuenta corriente (nivel 4)
  - Optimizar negocios (nivel 6)
  - Infraestructura (nivel 6)
- Central Eléctrica
  - Cuenta corriente (nivel 4)
  - Optimizar negocios (nivel 6)
  - Infraestructura (nivel 8)

Aparte podríamos añadir alguna otra investigación cómo Relacciones Exteriores, que tenga alguna relacción con lo que se puede hacer dentro de un clan y también sirva para desbloquear los últimos edificios.

Cuando un edificio no se puede comprar aparece con algo de transparencia, y un tooltip indica lo que falta, lo mismo con el resto de opciones que estuviesen bloqueadas (préstamos, etc).

Otra opción, sería investigar cada edificio, cómo dice @DamageESP , cada uno con su requisito de investigación básicas.

**Comment by NiciusB** [comment]
Me gusta esa idea :D Lo de las relacciones exteriores no estoy muy seguro de como funcionaría pero en principio está bien lo de tener investigaciones que no sean solo de upgradear cosas.
