### ISSUE TITLE
Idiomas (Translation)

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#63]
Despues de la Alpha o beta podemos hacer traducciones del juego.
Se pueden hacer con una función y un identificador de frase
Pongo un ejemplo:
Para decir _Historial de ataques_ se llama a la función _echot_ (por ejemplo) así:

``` php
<td><?=echot('historial_de_ataques')?></td>
```

Esa función devuelve un string con el texto en tu idioma.
El string lo puede coger de una tabla mysql como esta:

``` mysql
ID                            - TEXTO                   - IDIOMA
historial_de_ataques - Historial de ataques - es
historial_de_ataques - History of attacks - en
clan - clan - es
Clan - Clan - es
```

o bien de unos archivos php en una carpeta de idiomas:
**es.php**

``` php
$lstring['historial_de_ataques']="Historial de ataques";
$lstring['clan']="clan";
$lstring['Clan']="Clan";
```

**en.php**

``` php
$lstring['historial_de_ataques']="History of attacks";
```

La ventaja del mysql es que se podría traducir con ayuda de los usuarios fácilmente.
La ventaja del php es que sería mucho mas ligero y rápido que con mysql.

**Comment by DamageESP** [comment]
Opino que mejor con PHP, mucho más sencillo para nosotros.

**Comment by NiciusB** [comment]
Yo también creo que PHP es mejor, pero por temas de velocidad y carga del servidor.
Yo podría traducir al Inglés medianamente bien, y al Gallego perfectamente (aunque no sé si es muy útil jeje, pero a los portugueses les es mas fácil el gallego que el castellano)

**Comment by NiciusB** [comment]
Añadido todo el sistema de traducción.
Simplemente ir reemplazando textos de la web por la function echo getString('identificador')

Los archivos de idiomas están en /languages/id.php
