### ISSUE TITLE
Finanzas

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#64]
Creo que habría que hacer un poco más claro, los impuestos que se te están cobrando, lo que pierdes por el personal, etc. Una tabla cómo la que había en megamagnate, pero más detallada estaría bien.

Aparte, debería aparecer en alguna parte un aviso o algo, en el perfil o en el casino, cuando el casino te cobre intereses por las fichas. Por ejemplo una admiración roja al lado del número de fichas.

**Comment by NiciusB** [comment]
Eso podría ir en una tab de perfil.
Lo haré próximamente

**Comment by NiciusB** [comment]
En la tab de finanzas del perfil ya puedes ver en que se te vá el dinero xD
Le puse una chart circular, creo que hay que cambiarla algo

**Comment by Manuestaire** [comment]
Te ha quedao chulo, falta meterlo en tablas y esas cosas para que quede perfecto, lo del aviso de los intereses del casino dejadmelo a mí, que parece fácil de programar.

**Comment by Manuestaire** [comment]
Lo de las fichas del casino ya está hecho.

**Comment by NiciusB** [comment]
Pues bien...
Faltan tablas y estilos en las finanzas del perfil y ya terminamos

**Comment by DamageESP** [comment]
Alguien sabe por que pasa esto? 

http://gyazo.com/e0ba560b9c22c579009cd8a43f74627b

**Comment by NiciusB** [comment]
Porque has dado un préstamo.
Estoy solucionándolo.

**Comment by NiciusB** [comment]
Arreglado.

**Comment by NiciusB** [comment]
Falta algo aqui?

**Comment by Manuestaire** [comment]
darle formato, pero cierro ya que he dicho lo mismo en el hilo del perfil interno

**Comment by Manuestaire** [comment]
A ver aquí he dejado hecha la estructura pero faltan bastantes cosas más por hacer:
- Poner como desplegable los ingresos y gastos de cada tipo de edificio y de unidad. (Para más adelante)

**Comment by NiciusB** [comment]
Me ha quedado perfecto muejejeje
Cierro

**Comment by DamageESP** [comment]
:+1: @NiciusB
