### ISSUE TITLE
Bonificación por ascenso de posición en rank

### ISSUE THREAD

**Issue by DamageESP** [Manuestaire/megacorporation#65]
Estaría disponible a la semana de crear la cuenta, y consistiría en que por cada posición ascendida, te dan un bonus de dinero en proporción a tus ingresos, por ejemplo un 5%.

Para los tres primeros usuarios del rank también pienso que debería existir una condecoración, como por ejemplo el usuario que se mantenga entre estas posiciones durante más de 1 semana, por ejemplo gana acciones en bolsa o fama.

**Comment by Manuestaire** [comment]
Lo primero no lo veo claro, no porque no me guste la idea si no por tener que pensar en como influiría en el juego.

Lo segundo si que estoy completamente deacuerdo, pero eso lo podríamos incluir cuando se hagan los logros.

**Comment by NiciusB** [comment]
Lo siento mucho pero la primera me parece estúpida y la segunda injusta.
Lo que si que estaría bien son logros de mantenerse X tiempo en la primera pagina, los 10 primeros y los 3 primeros.

**Comment by DamageESP** [comment]
_infinitodesprecio_

**Comment by Manuestaire** [comment]
Relaccionado con #43 

Cierro este.
