### ISSUE TITLE
Perfil Interno

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#67]
Relaccionado con #25 

Como sabeís estoy reformando un poco el perfil interno, si alguno puede ir rellenando los campos de los rankings, con el símbolo de si ha subido o bajado...

**Comment by NiciusB** [comment]
Aviso de que /css/perfil.css y /css/common.css ya no funcionan, ya que están en la carpeta de temas.
Los que si que van son /css/tabs.css, rankings.css, jquery.css y algunos otros específicos (por ejemplo, edificios.css)

**Comment by Manuestaire** [comment]
si, los estilos los he metido en perfil_new.css

de todas formas, perfil.css lo quiero sacar de la cabecera, así que id pasando las cosas que necesiteís al common.css

**Comment by Manuestaire** [comment]
Falta:
- Gráficas:
  - Ingresos/gastos/beneficios
  - posiciones en rank
- Mover las gráficas a su sitio
- Mover la parte del pie chart a la pestaña de finanzas.
- Pasarle al pie chart los datos con puntos de miles y millones.
- Colocar las opciones de editar perfil en la pestaña opciones.

**Comment by NiciusB** [comment]
Me parece que todo funciona correctamente.
En 2 dias ya se verán las gráficas bien y si está todo correcto, cerramos

**Comment by Manuestaire** [comment]
Sólo falta dar formato a la pestaña de finanzas en cuanto lo haga cierro.

**Comment by Manuestaire** [comment]
Pensandolo mejor, cierro este y dejo abierto el de #64 Finanzas
