### ISSUE TITLE
Uservoice (feedback y soporte)

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#69]
Echadle un vistazo a esto: http://www.uservoice.com
Basicamente lo hace todo fácilisimo, la desventaja: la versión gratuita sólo admite un agente.

También puede ser interesante: http://www.linuxplanet.com/linuxplanet/reports/7125/1

**Comment by DamageESP** [comment]
No entiendo para que sirve eso. Si es para algo de tickets, ya esta hecho el sistema de soporte xD

**Comment by NiciusB** [comment]
Es como nuestro soporte, solo que mas bonito, con mas opciones y con un live chat.
Mi opinión es que no lo necesitamos

**Comment by Manuestaire** [comment]
@NiciusB eso es exactamente, a mí me llamó la atención por la api y ciertas funciones como lo de poder contestar desde el mail, las respuestas prealmacenadas y las notas.
