### ISSUE TITLE
Asistente para casinos

### ISSUE THREAD

**Issue by DamageESP** [Manuestaire/megacorporation#7]
Una nueva ventaja que costara una cantidad aun por determinar de influencia, y te permitira usar el autoclick del casino durante una semana, que tendras que volver a contratar los servicios del asistente.

**Comment by Manuestaire** [comment]
https://github.com/Manuestaire/megacorporation/issues/11

**Comment by NiciusB** [comment]
Hecho.

**Comment by Manuestaire** [comment]
Creo recordar que @DamageESP estaba buscando alguna cosa así: http://ios-checkboxes.awardwinningfjords.com/

**Comment by DamageESP** [comment]
Mola ! Hecho
