### ISSUE TITLE
Reemplazar Ranking de Influencia

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#70]
Creo que esto ya os lo comenté a alguno, pero parece un poco absurdo actualmente el ranking de influencia, desde que puede gastarse y emplease para comprar ventajas.

Yo propongo reemplazarlo por un ranking de tropas, cada unidad que tienes en ese momento añade 1 punto, independientemente de cual sea, si te atacan pierdes unidades, luego pierdes puntos. Para evitar su uso al inicio del juego, si se tienen menos de 30pt de tropas se muestra 0.

Otra opción sería hacer que el ranking de influencia no tenga en cuenta la que te has gastado en ventajas, y sólo la que ganas con edificios y ataques y la que pierdes en ataques.

**Comment by DamageESP** [comment]
Pero eso entonces revelaría la cantidad de guardias que tienes, no? :S

**Comment by Manuestaire** [comment]
Revela la cantidad total de unidades que tienes, tanto atacantes como defensivas, imposible distinguirlas.

PD: skype si puedes

**Comment by DamageESP** [comment]
Pero está claro que no vas a llevar saboteadores siempre encima... Demasiada información diría yo, sería una parte del espionaje

**Comment by NiciusB** [comment]
Yo creo que se puede hacer una columna con fama_gastada y para el ranking ese se suma la gastada y la actual.

**Comment by DamageESP** [comment]
Eso sí

**Comment by Manuestaire** [comment]
A ver, teneís que pensar que ese dato, sólo da el número total de unidades que tienes, por lo que se suman espías, y los 4 tipos distintos de tropas que hay, sabiendo sólo la suma total me parece imposible planificar un ataque así.

**Comment by NiciusB** [comment]
Vale, planteémonos esto de otra manera: Vas a la página 10 y buscas a alguien que esté en tu rango y con 0 tropas.
It's free!

**Comment by DamageESP** [comment]
No lo veo viable

**Comment by NiciusB** [comment]
Añadido el influencia_gastada y completamente funcional en los rankings de usuarios y clanes

**Comment by NiciusB** [comment]
Manu, el ranking de unidades en el ogame va guay, porque cuando fabricas naves te quedas con ellas hasta que se destruyen, pero en este juego las tropas van y vienen momentáneamente por lo que no es muy viable este tipo de ranking...

**Comment by Manuestaire** [comment]
oki
