### ISSUE TITLE
Zona novatos

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#71]
Parece ser que sin zona novatos, avanzar en los primeros días se hace muy duro.
Propongo que hasta los 450k€ de ingresos no suban los precios de los edificios, y que hasta esa misma cantidad no puedas atacar ni recibir ataques.

**Comment by Manuestaire** [comment]
Lo de los ataques si lo veo bien, lo de los edificios es una cosa que nunca me terminó de convencer...

**Comment by NiciusB** [comment]
Ya no pueden hacer ni recibir ataques.
El precio de los edificios sigue siendo el inicial hasta pasar el límite.

Variable $constante['limite_zona_newbie'] en las constantes, y definida en 450k.
Parece ser que está terminado

**Comment by Manuestaire** [comment]
No se pueden comprar edificios, aperece un alert con su precio.

**Comment by Manuestaire** [comment]
PD: yo creo que es mejor que desde el principio, la gente sepa que los edifiicios van escalando en precio, y mantenerlo sólo favorece a los que ya lo saben, y lo aprovechan para mejorar un sólo edificio a lo bestia.

Para compensar el avance lento al principio del juego, yo propondría empezar con más dinero.

**Comment by NiciusB** [comment]
Yo propondría hacer un buen tutorial simple y divertido para que los que no saben entiendan de que va el juego y no pasen de él y lo cierren.
En el mismo la gente podría ver diferentes estrategias para avanzar rápido, defenderte bien, espiar correctamente...

**Comment by Manuestaire** [comment]
Lo del tutorial, lo veo bien, yo lo implementaría junto con los logros...

Pero vamos, a ver si llegamos a un acuerdo con lo de los edificios y cerramos esto.

**Comment by DamageESP** [comment]
No me para de salir: no puedes comprar más edificios de este tipo, y tengo 0 Pubs :/ xDD

**Comment by NiciusB** [comment]
Pues yo creo que la zona newbie beneficia a todo el mundo, además, bien explicada ayudaría incluso mas a los novatos a controlar lo de comprar edificios y eso jajaja

**Comment by NiciusB** [comment]
Los límites de edificios que he puestos son un tanto aleatorios. habría que ponerlos bien jaja

**Comment by Manuestaire** [comment]
@NiciusB cómo te va a ayudar a controlar la compra de edificios si te aleja de los precios reales?
De lo de los ataques si estoy deacuerdo pero lo de los precios, no me parece que ayyude a los que verdaderamente son newbies, si no a los que ya saben jugar.

**Comment by NiciusB** [comment]
Bueno, esto ya está terminado, no?
Yo creo que se pude cerrar

**Comment by DamageESP** [comment]
Yep.
