### ISSUE TITLE
subnormales, subnormales everywhere

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#72]
Buenos días, compañeros. Hoy entré al juego tan tranquilo pensando que estamos a punto de abrir la versión Alpha cuando me doy cuenta de que al hacer login me abre una pestaña nueva... vaya debe haber sido un error mío, pienso. será que no ha cargado la página bien.
Entonces es cuando voy a mis edificios y reparo en que, a pesar de estar en la zona newbie, los precios salen como si no lo estuviera. ¿Que cojones?, me pregunto, ¿Porque la han quitado sin avisar ni nada?
En ese momento pruebo a comprar un edificio, y imaginen mi sorpresa al ver que TAMBIÉN SE HA ABIERTO UNA NUEVA PESTAÑA.
Lo peor de todo no era eso, si no que al fijarme en el código me doy cuenta de que en la pagina de edificios de DICE EL PRECIO COMO SI NO LO ESTUVIERAS, pero TE COBRA COMO SI ESTUVIERAS EN ZONA NEWBIE.

Para colmo, me doy cuenta de que alguien ha borrado TODAS las iframes que hacían que pudieras hacer acciones sin abrirte una nueva pestaña o recargar la página en el clan, edificios, login, casinos...

Entonces es cuando, cabreado, vengo a Github y escribo esta issue.
Muchas gracias

**Comment by Manuestaire** [comment]
Yo desde ayer no toco archivos, y sólo toqué un css

**Comment by DamageESP** [comment]
Yo desde hace semanas no subo un archivo al server, solo para lo de los css del skyline, asi que a mi no me mires xD

**Comment by Manuestaire** [comment]
Pero que han desaparecido los archivos o las llamadas?

De verdad que esque no entiendo nada, ¿No hay logs del ftp?

El vídeo de youtube del index tampoco está, y los iconos de las acciones están los viejos :S

**Comment by NiciusB** [comment]
No sabéis como me alegra que no fuerais vosotros...
Debe ser un error de los subnormales del hosting

**Comment by NiciusB** [comment]
Parece como si todo hubiera vuelto a hace unos días D:
El perfil vuelve a ser como estaba antes...
Intentaré arreglarlo todo :D

**Comment by Manuestaire** [comment]
Tienes copia?

**Comment by NiciusB** [comment]
Es super-extraño... parece que nos hayan hackeado jajaja
No tengo copia, pero ya arreglé un iframe raro que salía en todos los js por alguna razón y que llevaba a una pagina de artes marciales sobrecargada en 000webhost.
Tambien he arreglado los iframes rotos y los he concentrado en un iframe para ahorrar lineas, y también los edificios con zona newbie
Creo que lo único que se ha perdido es el perfil y las imágenes de las operaciones en el rank y eso...

EDIT: Arreglado el foro, que también daba problemas

**Comment by NiciusB** [comment]
Ok... buen trabajo muchachos!
Cierro
