### ISSUE TITLE
Mejoras en la cabecera

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#74]
Pasar los enlaces al foro y soporte, para que salgan bajo el link a salir.

**Comment by NiciusB** [comment]
En la default?
EDIT: En el default ya está cambiado

**Comment by Manuestaire** [comment]
Yo creo que es más cómodo así, por lo que recomiendo también cambiarlo en el skyline, pero ahí ya a vuestro gusto. Hay un problemilla con los estilos, veré si lo puedo solucionar...

**Comment by Manuestaire** [comment]
Solucionado
