### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#75]
Lista de cambios para esta versión:
# Cosas que hay que hacer en live

-Cambiar precios de unidades (constantes_juego.php)
-Añadir Nostalgic a la lista de temas (constantes_juego.php)
# Bugs críticos
- [x] Solucionados varios bugs que daban carga innecesaria al servidor
- [x] El premio mensual de sabotajes ya da la influencia correspondiente
- [x] El premio semanal de mejores franquicias ya da la influencia correspondiente
- [ ] Precios de unidades mal puestos
- [x] El botón de ataque no aparecía en los rankings 
- [x] Arreglado un bug, por el que se podía ignorar la espera entre tiradas del casino.
- [x] Ya puedes atacar a usuarios sin clan si no tienes clan (Salía un error diciendo "Este usuario es de tu clan!")
- [x] Arreglado un bug que permitia poner iniciales de clan con mas de 4 caracteres
# Errores
- [x] Las fechas en los gráficos ya no tienen un mes de más
- [x] Estilo de edificios aplicado a Inversiones y Entrenar unidades
- [x] Pequeño error al buscar un usuario en el rank que no mostraba el selector de paginas.
- [x] Ya es posible cambiar la imagen de Clan.
- [x] Textos descriptivos mal puestos
- [x] Estilo de textareas cambiado en Google Chrome
- [ ] Los impuestos de clanes no se tienen en cuenta en las gráficas como gastos
- [ ] Se han corregido los errores visuales de los anuncios, y preparado para la personalización de colores.
# Nuevas Características
- [x] Al recargar la página, si hay pestañas, volverás a la última pestaña
- [x] Ahora puedes ver quién es el presidente de los clanes
- [x] Ataques y espionajes hechos directamente desde el ranking
- [x] Añadido número de miembros en el Ranking de Clanes
- [x] Nuevo tema: Nostalgic
- [ ] Añadidas opciones de tema (Aplazado)
- [x] Finalización de ataques instantánea (al llegar a 0, se terminan y no hay un "Terminando...") (Cuando se haga hay que eliminar el archivo /cron/minuto.php , ya que lo que él hace se hará en otro sitio)
- [x] Añadido número de edificios y unidades en _Finanzas_
- [x]  Añadida nueva gráfica en Finanzas de costes de mantenimiento de tropas
- [x] Añadido botón de Responder Mensaje.
- [x] Las recompensas del concurso de criminales, ahora están más equilibradas con el progreso del juego
- [x] Ahora te avisa cuando hay mensajes no leídos en el foro del clan
- [x] Añadidos links en determinadas características que quizás sean difíciles de entender a posts que las expliquen en el foro
# Cambios Menores
- [ ] Cambios de estilo en el ranking de usuarios
- [x] Sutil aumento de la posibilidad de ganar premios (no botes) en el Casino
- [x] Cambiado Comprar unidades por Contratar unidades
- [x] Auto-login al foro al conectarte en el juego
- [x] Eliminada referencia a unos archivos inexistentes e innecesarios
- [x] Optimizada carga del perfil
- [x] Eliminadas algunas investigaciones en Entrenar Unidades hasta que sean funcionales
- [x] Eliminada información no necesaria en el panel de administración de clanes
- [x] Añadidas páginas 404, 403 y 500

**Comment by NiciusB** [comment]
En el perfil, los datos de subidas y bajadas dan numeros extraños cuando deberían ser 0, no?

**Comment by NiciusB** [comment]
Solucionado.

**Comment by Manuestaire** [comment]
No borreís la lista de bugs solucionador, para poder luego hacer changelogs y esas cosas.

**Comment by Manuestaire** [comment]
Actualizado

**Comment by Manuestaire** [comment]
Actualizado

**Comment by DamageESP** [comment]
Actualizado

**Comment by DamageESP** [comment]
Añadido bug crítico

**Comment by Manuestaire** [comment]
Nuno, has dejado mal los clanes, muchos errores visuales...

Respecto a las interrogaciones esas, creo que de momento son prescindibles.
