### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by DamageESP** [Manuestaire/megacorporation#80]
Bugs
La descripción del concurso de franquicias ya se muestra correctamente.
Los gastos no se mostraban correctamente en una de las gráficas.
Ahora es necesario tener más de 0 puntos, para poder ganar el concurso de criminales. (para evitar premios aleatorios en partidas recién empezadas)
Ahora no se reparten premios de Mejores Franquicias si no se tiene más del máximo de edificios de la zona newbie (512, 256, 128, etc.)
Corregido el Bug que alteraba el orden de los premios en mejores franquicias.
El ranking ahora hace menos querys a la base de datos y no sobrecarga el servidor
Corregido el color del degradado del feed, en Internet Explorer
Optimizada la sección de Ventajas y aplicado el estilo de edificios
Arreglado bug crítico que echaba a todos los miembros de un clan al salir un usuario de él.
Ya no puedes pedir un PNA a tu propio clan
Arreglados textos en las novedades
Corregidos los textos en Mejores Criminales
Solucionado el Bug de edificios destruídos ( viewtopic.php?f=14&t=28 )
Solucionado un bug por el que la acción de espiar sólo funcionaba en el ranking
Solucionado bug que calculaba mal los impuestos de clan en la tab de finanzas del perfil ( viewtopic.php?f=14&p=261 )

Nuevas Características
Nueva pagina de conexión
Nuevo reporte animado en la Finalización de ataques
Nuevo diseño del perfil visible al resto de usuarios (y nueva opción de perfil "Lema")
Ahora se muestra el ataque y defensa de cada unidad en la página de Contratar Unidades
Añadida pestaña de Mensajes Enviados
Añadido reloj hora servidor (España)
Nuevo diseño en los mensajes
Añadidos dos temas opcionales al foro

Cambios Menores
Ajustados precio y duración de la ventaja de autoclick en el Casino
Añadido enlace a Perfil en Comunidad
Añadido mensaje que te avisa si tienes una operación activa
Eliminado molesto alert cada vez que te saltas el tiempo de apuesta en el casino
Movido orden de carga en el servidor para que al ganar un logro no haya errores en el documento
Ahora los links al visor de ataques están en negrita
Ahora cuando aparece tu nombre el link lleva al Perfil en lugar del Ranking
Reducido el tamaño del nombre del rango en cambiar rangos (solo presidentes de clanes)
Ahora los tooltips se ajustan a la posición del ratón
Se han añadido links al ranking en distintas partes de la página (en el tema default)

**Comment by DamageESP** [comment]
Lo de los ataques creo que no se hará por el momento. Por mí podemos sacar esta versión cuanto antes.

**Comment by Manuestaire** [comment]
A ver si @NiciusB puede echarle un ojo al Bug de edificios destruídos y ya con eso, lo sacamos.

**Comment by DamageESP** [comment]
Por cierto, lo de el alert que te dice el num max de edificios que puedes comprar parece que no funciona, a mi siempre me dice 0.
