### ISSUE TITLE
Nuevo Login page

### ISSUE THREAD

**Issue by NiciusB** [Manuestaire/megacorporation#83]
Realmente, la actual es muy fea.
Propongo hacer una pagina de login basada en la pagina de registro y de "equipo"

**Comment by Manuestaire** [comment]
No lo considero importante, pero me parece bien, es algo que tenemos que hacer...

**Comment by DamageESP** [comment]
Sip, hay que hacer una más currada, que es lo primero que verá la gente cuando entra.
