### ISSUE TITLE
Reducir el string de los botes en los anuncios

### ISSUE THREAD

**Issue by Manuestaire** [Manuestaire/megacorporation#9]
Formato del tipo:

NOMBRE ha ganado NÚMERO fichas en el casino CASINO.

Tener en cuenta que la fama ganada es irrelevante.

**Comment by NiciusB** [comment]
Lo he cambiado:

Bote [ 18:54 ]  

tathtat ha ganado un bote con 32.085 fichas en el casino Casino $$Pasta$Gansa$$

Ya no ocupa todo... creo que lo cierro :P

**Comment by Manuestaire** [comment]
Soy el único al que con le suena raro aquí:  un bote con 32.085 fichas

mejor un bote de 32.000 fichas no?

**Comment by NiciusB** [comment]
No se, a mi me suena bien... di alguna forma de hacerlo entonces... hacemos un round para que salgan hasta los miles y nada mas?

**Comment by Manuestaire** [comment]
digo que lo que me suena mal es la preposición, que sería un bote DE nosequantas fichas.

**Comment by NiciusB** [comment]
Ah LOL pues entonces lo cambio ahora mismo.
Solucionado!

**Comment by Manuestaire** [comment]
Acabo de entrar y veo el mismo string de siempre.

**Comment by NiciusB** [comment]
El string de las novedades es un texto, no cambia lo ya puesto, pero a partir de ahora saldrán todos como:
PERSONA ha ganado un bote con X fichas en el casino NOMBRE
